### ISSUE TITLE
Building with MSVC toolchain under Windows

### ISSUE THREAD

**Issue by bzindovic** [tov/libffi-rs#79]
I encounter some strange behavior under Windows while using clang that is bundled with Visual studio; the solution to the original issue was reported [here](https://github.com/rsmpi/rsmpi/issues/163#issuecomment-1572592658). With Visual Studio 2022, official LLVM 15.0.7 and rust 1.69, I've managed to compile a project using `libffi-rs` and `libffi-sys-rs`. After updating the rust toolchain to 1.70, I get the error:

`libffi/src/x86/win64_intel.S(2): fatal error C1083: Cannot open include file: 'fficonfig.h': No such file or directory`

After trying various LLVM combos (none of them worked), I reverted to LLVM 15.0.7 and Rust 1.69, but it still fails with the same message with missing `fficonfig.h`.

Has anyone had this kind of issue under Windows?

**Comment by mdekstrand** [comment]
Can confirm. 3535bd9 fixes it.

**Comment by jedbrown** [comment]
I think this can close now that #81 has merged (thanks). (There was a network error in the most recent pipeline, but it seems clearly unrelated.)
